# Jekyll configuration

name: Halil ARI


# Url is currently only used only for the RSS feed in feed.xml
#url: http://streetturtle.github.io
url: https://halilari.github.io

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ""
gems:
  - jekyll-paginate
  - jekyll-sitemap
share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: halilari
  linkedin: halilari
  twitter: HalilAri3

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-97208202-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:

tag_page_layout: tag_index
tag_page_dir: site/tag

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: halilari.github.io
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: "/page:num/"

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
